.TH adt\-run 1 2006 autodebtest "Linux Programmer's Manual"
.SH NAME
adt\-run \- test an installed binary package using the package's tests
.SH SYNOPSYS
.B adt\-run
.IR options ...
.B \-\-\-
.I virt\-server
.RI [ virt\-server\-arg ...]
.br
.SH DESCRIPTION
.B adt\-run
is the program for invoking the autodebtest package testing machinery.

autodebtest is a facility for testing binary packages, as installed on
a system (such as a testbed system).  The tests are those supplied in
the source package.

adt\-run runs each test supplied by a particular package and reports
the results.  It drives the specified virtualisation regime as
appropriate, and parses the test description metadata, and arranges
for data to be copied to and from the testbed as required.

adt\-run should be invoked (unless options to the contrary are
supplied) in the top level directory of the built source tree, on the
host.  The package should be installed on the testbed.

.SH OPTIONS
.TP
.BR \-\-build\-tree [ \-tb ] " " \fIdirectory\fR
Specifies that the built source tree can be found in
.IR directory .
(Default: adt\-run's current directory, on the host.)
.TP
.BR \-\-control [ \-tb ] " " \fIcontrol\fR
Specifies that
.I control
should be used as the test control file instead of
.B debian/tests/control
in the build tree.  Note that it is not an error for this file not to
exist; that just means that there are no tests.
.TP
.BR \-d " | " \-\-debug
Enables debugging output.  Probably not hugely interesting.
.TP
\fB\-\-\-\fR \fIvirt\-server virt\-server\-arg\fR...
Specifies the virtualisation regime server, as a command and arguments
to invoke.  All the remaining arguments and options after
.B \-\-\-
are passed to the virtualisation server program.

.SS NOTES
Some options which come in variants with and without
.BR \-tb .
These specify paths on the testbed and the host, respectively.  The
data will be copied by
.B adt\-run
to where it is needed.

.SH OUTPUT FORMAT
During a normal test run, one line is printed for each test.  This
consists of the name of the test, some horizontal whitespace, and
either
.B PASS
or
.BR FAIL " reason"
or
.BR SKIP " reason"
where the pass/fail indication is separated by any reason by some
horizontal whitespace.

Sometimes a
.B SKIP
will be reported when the name of the test is not known or not
applicable: for example, when there are no tests in the package, or a
there is a test stanza which contains features not understood by this
version of
.BR adt\-run .
In this case
.B *
will appear where the name of the test should be.

.SH EXIT STATUS
0	all tests passed
.br
2	at least one test skipped
.br
4	at least one test failed
.br
6	at least one test failed and at least one test skipped
.br
8	no tests in this package
.br
12	erroneous package
.br
16	testbed failure
.br
20	other unexpected failures including bad usage

.SH SEE ALSO
\fBadt\-virt\-chroot\fR(1)

.SH BUGS
This tool still lacks many important features.

.SH AUTHORS AND COPYRIGHT
This manpage is part of autodebtest, a tool for testing Debian binary
packages.  autodebtest is Copyright (C) 2006 Canonical Ltd and others.

See \fB/usr/share/doc/autodebtest/CREDTIS\fR for the list of
contributors and full copying conditions.
