#!/bin/bash
#
#  This script expects to be given one argument, the name
#  of the config file which will set the PATH if necessary
#  and cd to the appropriate playground.  This and all
#  remaining arguments are passed to a-t-r.

set -e
. "$1"

exec >>var/overall.log 2>&1
test -f go
with-lock-ex -q cronjob-lock \
 adt-testreport-runloop "$@" max_test_count=100
