#!/bin/bash
#
#  This script expects to be given at least two arguments:
#     directory to cd to
#     main config file for adt-testreport-runloop which sets PATH if need be
#     remaining arguments are passed through to a-t-r unchanged

set -e

export suppressions_kind=debbugs
export suppressions_debbugs_soap=Debbugs/SOAP
export suppressions_debbugs_uri=http://bugs.debian.org/cgi-bin/soap.cgi
export suppressions_usertag_owner=autopkgtest@packages.debian.org
export suppressions_usertag_name=autopkgtest

cd "$1"
shift
. "$1"

: "${suppressions_file_to_fetch:=${suppresspackages:-suppressions}}"
export suppressions_file_to_fetch

: "${suppressions_file_to_lock:=$suppressions_file_to_fetch-lock}"

echo 'locking'

with-lock-ex -f "$suppressions_file_to_lock" bash -c '
	. "$1"

	f="$suppressions_file_to_fetch"

	export distro

	echo fetching
	${suppressions_fetch:-adt-suppressions-fetch-$suppressions_kind} \
		>"$f".new

	echo results
	nl -ba -- "$f".new

	if ! test -s "$f".new;
	then
		echo >&2 "NO SUPPRESSIONS - PROBABLY WENT WRONG"
		exit 1
	fi

	mv -- "$f".new "$f"

	if [ "x$suppressions_copy_destination" != x ]; then
		echo "uploading"
		RSYNC_RSH=ssh rsync "$f" "$suppressions_copy_destination"
	fi
	echo done.
' x "$@"
